import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { LogoutIcon } from '@heroicons/react/outline'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="px-4 py-5 my-5 text-center">
        <LogoutIcon width="72" height="72" />
        <h1 className="display-3 fw-bold">Smart Signout</h1>
        <div className="col-lg-6 mx-auto">
          <p className="lead mb-4">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Asperiores harum nostrum libero, odio iusto blanditiis excepturi ipsam reprehenderit cumque ipsa?</p>
          <div className="d-grid gap-2 d-sm-flex justify-content-sm-center">
            <Link href="/signout">
              <button type="button" className="btn btn-primary btn-lg px-4 gap-3" href="./bs">Smart Signout</button>
            </Link>
            <button type="button" className="btn btn-outline-secondary btn-lg px-4">Manual Signout</button>
          </div>
        </div>
      </div>
      {/* <footer className={styles.footer}>
        <a href="http://jackmhny.xyz">Created by Jack Mahoney</a>
      </footer> */}
    </div>
  )
}
